#include <iostream>

int main() {
    int a = 10;
    int b = 5;
    
    int suma = a + b;
    int roznica = a - b;
    int iloczyn = a * b;
    
    std::cout << "Liczba 1: " << a << std::endl;
    std::cout << "Liczba 2: " << b << std::endl;
    std::cout << "Suma: " << suma << std::endl;
    std::cout << "Roznica: " << roznica << std::endl;
    std::cout << "Iloczyn: " << iloczyn << std::endl;
    
    return 0;
}